name: Publish to NPM registry

on:
  push:
    branches:
      - main

jobs:
  publish:
    needs: checker
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Node.js with the specified version from .nvmrc
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"

      # Publish on npm
      - name: Publish the package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
